# -*- coding: utf-8 -*-
"""Country tag display names.

The analyzer prefers localization files when they are available, and falls back
to a compact built-in map for common Victoria 3 tags.
"""

from __future__ import annotations

import re
from pathlib import Path

BUILTIN_COUNTRY_NAMES = {
    "ABU": "特鲁西尔诸国",
    "ACE": "亚齐",
    "ACH": "阿乔利",
    "AFG": "阿富汗",
    "ALD": "阿尔及利亚",
    "AMZ": "亚马逊尼亚",
    "ANH": "安哈尔特",
    "ANK": "安科莱",
    "ANL": "安达卢西亚",
    "ARA": "阿拉伯",
    "ARG": "阿根廷",
    "ARM": "亚美尼亚",
    "ASA": "新非洲",
    "AST": "澳大利亚",
    "AUS": "奥地利",
    "AWA": "奥德",
    "AWS": "奥萨",
    "AYI": "阿尼",
    "AZB": "阿塞拜疆",
    "BAB": "巴比伦",
    "BAD": "巴登",
    "BAL": "巴厘",
    "BAS": "巴斯塔尔",
    "BAV": "巴伐利亚",
    "BEL": "比利时",
    "BEN": "贝宁",
    "BER": "巴罗达",
    "BHO": "博帕尔",
    "BIC": "东印度公司",
    "BKN": "布哈拉",
    "BLA": "毕拉",
    "BLE": "鲍勒",
    "BLG": "布隆岸",
    "BMB": "本巴",
    "BOH": "波希米亚",
    "BOL": "玻利维亚",
    "BOR": "博尔努",
    "BOS": "波斯尼亚",
    "BRA": "巴西",
    "BRE": "不来梅",
    "BRN": "博拉纳",
    "BRU": "文莱",
    "BRZ": "巴西",
    "BUG": "布干达",
    "BUK": "布哈拉",
    "BUL": "保加利亚",
    "BUN": "本德尔坎德",
    "BUR": "缅甸",
    "BYE": "白俄罗斯",
    "CAL": "加利福尼亚",
    "CAM": "柬埔寨",
    "CAN": "加拿大",
    "CAS": "卡斯蒂利亚",
    "CAT": "加泰罗尼亚",
    "CAU": "外高加索",
    "CEY": "锡兰",
    "CHE": "切罗基",
    "CHI": "中国",
    "CHL": "智利",
    "CHP": "占婆萨",
    "CLM": "哥伦比亚",
    "CMI": "清迈",
    "CNG": "刚果",
    "COB": "萨克森-科堡-哥达",
    "COL": "哥伦比亚",
    "COM": "科曼奇",
    "COS": "哥斯达黎加",
    "CRE": "克里特",
    "CRI": "克里米亚",
    "CRO": "克罗地亚",
    "CUB": "古巴",
    "CYP": "塞浦路斯",
    "CZH": "捷克",
    "DAH": "达荷美",
    "DAI": "大南",
    "DEN": "丹麦",
    "DES": "德塞雷特",
    "DOM": "圣多明各",
    "DON": "顿河哥萨克",
    "DZH": "准噶尔",
    "ECU": "厄瓜多尔",
    "EGY": "埃及",
    "ELS": "萨尔瓦多",
    "ENG": "英国",
    "EST": "爱沙尼亚",
    "ETH": "埃塞俄比亚",
    "EWE": "埃维",
    "FIN": "芬兰",
    "FJI": "斐济",
    "FLA": "佛兰德",
    "FRA": "法国",
    "FRM": "法兰克福",
    "GBR": "英国",
    "GCO": "大哥伦比亚",
    "GEO": "格鲁吉亚",
    "GER": "德国",
    "GRE": "希腊",
    "GUA": "危地马拉",
    "GWA": "瓜廖尔",
    "HAN": "汉诺威",
    "HAR": "哈勒尔",
    "HAU": "豪萨",
    "HAW": "夏威夷",
    "HBC": "哈德逊湾公司",
    "HES": "黑森",
    "HEK": "黑森-卡塞尔",
    "HND": "印度",
    "BHT": "巴拉特",
    "HOB": "霍比奥",
    "HOL": "荷尔斯泰因",
    "HON": "洪都拉斯",
    "HUN": "匈牙利",
    "HYD": "海得拉巴",
    "IBE": "伊比利亚",
    "ICL": "冰岛",
    "IDN": "印度尼西亚",
    "IND": "印多尔",
    "ION": "爱奥尼亚群岛",
    "IRE": "爱尔兰",
    "IRQ": "伊拉克",
    "ISR": "以色列",
    "ITA": "意大利",
    "JAI": "斋浦尔",
    "JAM": "牙买加",
    "JAN": "扬马延",
    "JAP": "日本",
    "JAV": "爪哇",
    "JLF": "杰洛夫",
    "JOH": "柔佛",
    "KAB": "喀布尔",
    "KAL": "卡拉特",
    "KAN": "坎大哈",
    "KAS": "克什米尔",
    "KAZ": "哈萨克",
    "KBD": "卡巴杜古",
    "KBU": "卡布",
    "KFA": "卡法",
    "KHI": "希瓦",
    "KHM": "高棉",
    "KNG": "刚果",
    "KOK": "浩罕",
    "KOR": "朝鲜",
    "KRA": "克拉科夫",
    "KRG": "卡拉格韦",
    "KRT": "卡尔塔",
    "KRU": "克鲁",
    "KUT": "卡奇",
    "KZH": "小玉兹",
    "LBA": "卢巴",
    "LGA": "莱加",
    "LIB": "利比里亚",
    "LIP": "利珀",
    "LIT": "立陶宛",
    "LKT": "拉科塔",
    "LND": "隆达",
    "LNG": "卢安果",
    "LOM": "伦巴第",
    "LUA": "琅勃拉邦",
    "LUB": "吕贝克",
    "LUC": "卢卡",
    "LUO": "罗",
    "LUX": "卢森堡",
    "MAD": "马达加斯加",
    "MAK": "马夸",
    "MAN": "曼哈顿公社",
    "MAY": "玛雅",
    "MCH": "满洲",
    "MCR": "密克罗尼西亚",
    "MDK": "曼丁卡",
    "MEC": "梅克伦堡",
    "MST": "梅克伦堡-施特雷利茨",
    "MEX": "墨西哥",
    "MGL": "蒙古",
    "MJT": "马吉尔廷",
    "MKT": "米斯基托",
    "MLI": "马里",
    "MLT": "马耳他",
    "MNC": "马尼卡",
    "MNG": "明",
    "MOD": "摩德纳",
    "MOL": "摩尔达维亚",
    "MON": "黑山",
    "MOR": "摩洛哥",
    "MOS": "莫西",
    "MST": "梅克伦堡-施特雷利茨",
    "MUG": "印度斯坦",
    "MYS": "迈索尔",
    "NAG": "那格浦尔",
    "NAH": "阿纳瓦克",
    "NAL": "纳塔利亚",
    "NAM": "纳马",
    "NAS": "拿骚",
    "NAV": "纳瓦拉",
    "NEJ": "内志",
    "NEP": "尼泊尔",
    "NET": "荷兰",
    "NEW": "纽芬兰",
    "NGF": "北德意志邦联",
    "NIC": "尼加拉瓜",
    "NOR": "挪威",
    "NRU": "瑙鲁",
    "NTO": "恩加蒂托阿",
    "NVJ": "纳瓦霍",
    "NYM": "尼亚姆韦齐",
    "NZL": "新西兰",
    "OLD": "奥尔登堡",
    "OMA": "阿曼",
    "ORA": "奥兰治",
    "ORG": "俄勒冈",
    "ORI": "奥里萨",
    "OTO": "奥托",
    "OTT": "奥斯曼",
    "PAP": "教宗国",
    "PAR": "帕尔马",
    "PAT": "巴塔哥尼亚",
    "PER": "波斯",
    "PEU": "秘鲁",
    "PHI": "菲律宾",
    "PLC": "波兰-立陶宛",
    "PNM": "巴拿马",
    "POL": "波兰",
    "POR": "葡萄牙",
    "PRG": "巴拉圭",
    "PRU": "普鲁士",
    "PUE": "普韦布洛",
    "PUN": "旁遮普",
    "QAS": "卡西米尔",
    "QUE": "魁北克",
    "REB": "叛军",
    "RHE": "莱茵兰",
    "ROM": "罗马尼亚",
    "RUS": "俄罗斯",
    "RUT": "鲁塞尼亚",
    "SAR": "撒丁-皮埃蒙特",
    "SAS": "南澳大利亚",
    "SAX": "萨克森",
    "SCA": "斯堪的纳维亚",
    "SCH": "石勒苏益格",
    "SGF": "南德意志邦联",
    "SHI": "西姆拉",
    "SIA": "暹罗",
    "SIC": "两西西里",
    "SIK": "锡金",
    "SIL": "塞拉利昂",
    "SIN": "信德",
    "SKH": "萨哈林",
    "SLO": "斯洛文尼亚",
    "SLV": "斯洛伐克",
    "SOK": "索科托",
    "SPA": "西班牙",
    "SRB": "塞尔维亚",
    "SWE": "瑞典",
    "SWI": "瑞士",
    "TBI": "提贝斯提",
    "TEX": "得克萨斯",
    "TGR": "提格雷",
    "TIB": "西藏",
    "TKE": "特克",
    "TNG": "汤加",
    "TRH": "图兰",
    "TUR": "土耳其",
    "TUS": "托斯卡纳",
    "TUV": "图瓦",
    "UCA": "中美洲",
    "UKR": "乌克兰",
    "UBD": "波罗的联合公国",
    "URU": "乌拉圭",
    "USA": "美国",
    "VEN": "威尼斯",
    "VIE": "越南",
    "WAD": "瓦代",
    "WAL": "瓦拉几亚",
    "WEI": "魏玛",
    "WES": "威斯特伐利亚",
    "WIN": "西印度群岛",
    "WLD": "瓦尔德克",
    "WLG": "魏勒加",
    "WLO": "沃洛",
    "WUR": "符腾堡",
    "XIN": "维吾尔斯坦",
    "YEM": "也门",
    "YUE": "粤",
    "ZAI": "阿扎尔",
    "ZAN": "桑给巴尔",
    "ZUL": "祖鲁",
}


def _candidate_localization_files(project_root: Path | None = None) -> list[Path]:
    roots = []
    if project_root:
        roots.extend([project_root, project_root / "game"])
    roots.extend(
        [
            Path("D:/steam/steamapps/common/Victoria 3"),
            Path("C:/Program Files (x86)/Steam/steamapps/common/Victoria 3"),
        ]
    )
    patterns = [
        "game/localization/simp_chinese/*countries*.yml",
        "game/localization/simp_chinese/**/*.yml",
        "localization/simp_chinese/*countries*.yml",
        "localization/simp_chinese/**/*.yml",
        "**/countries_l_simp_chinese.yml",
    ]
    files: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for pattern in patterns:
            files.extend(path for path in root.glob(pattern) if path.is_file())
    return list(dict.fromkeys(files))


def load_country_names(project_root: Path | None = None) -> dict[str, str]:
    names = dict(BUILTIN_COUNTRY_NAMES)
    pattern = re.compile(r'^\s*([A-Z][A-Z0-9_]{2,})\s*:\d*\s+"([^"]+)"')
    for path in _candidate_localization_files(project_root):
        try:
            text = path.read_text(encoding="utf-8-sig", errors="ignore")
        except OSError:
            continue
        for line in text.splitlines():
            match = pattern.match(line)
            if match:
                names[match.group(1)] = match.group(2).strip()
    return names


def display_name(tag: object, names: dict[str, str] | None = None) -> str:
    raw = str(tag or "").strip().strip('"')
    clean = raw.upper()
    if not clean:
        return "未知国家"
    if not re.fullmatch(r"[A-Z][A-Z0-9_]{2,5}", clean):
        return raw
    lookup = names or BUILTIN_COUNTRY_NAMES
    return lookup.get(clean, "未命名国家")


def label(tag: object, names: dict[str, str] | None = None) -> str:
    raw = str(tag or "").strip().strip('"')
    clean = raw.upper()
    name = display_name(clean, names)
    if not clean:
        return name
    if not re.fullmatch(r"[A-Z][A-Z0-9_]{2,5}", clean):
        return raw
    return f"{name}（{clean}）"
