name: ci

on:
  push:
  pull_request:

jobs:
  python-compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Compile
        run: python -m py_compile analyze.py launcher.py
